version: '3.8'

services:
  db:
    image: postgres
    container_name: db_container
    ports:
      - "5432:5432"
    volumes:
      - db_vol:/data/db
    environment:
      POSTGRES_USER: karan
      POSTGRES_PASSWORD: thakur
      POSTGRES_DB: karan_db

  paytm:
    image: thakurkaran007/paytm:latest
    container_name: next_app
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgresql://karan:thakur@db_container:5432/karan_db"
      RESEND_KEY: "re_NjiVXpsH_LKSwqhq2517KaaS7uz5YQk5C"
      AUTH_SECRET: "secret"
      GITHUB_ID: "Ov23liBbq1MU8oy63qYC"
      GITHUB_SECRET: "74c2c9a2a09a9a14c28de384d791d529c4a85e88"
      GOOGLE_SECRET: "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GOCSPX-0tVFybGDlpGzh75vTONxYowVofQe"
      GOOGLE_ID: "157938167523-94a6nschvs2a9bfe1907b89v8qrt5rfq.apps.googleusercontent.com"
      DOMAIN: "thakurkaran.xyz"
    depends_on:
      - db

volumes:
  db_vol: