name: Build and Deploy to DockerHub

on:
  push:
    branches:
      - master

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./docker/Dockerfile.user-app
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/paytm:latest

            - name: Verify Pushed Image
              run: docker pull ${{ secrets.DOCKER_USERNAME }}/paytm:latest
